version: '3.8'

# mkdir -p ${HOME}/jdk7u && DISTRO=centos DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=7 docker-compose -f docker-compose.yml run --rm --build jdk
# mkdir -p ${HOME}/jdk8u && DISTRO=centos DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=8 docker-compose -f docker-compose.yml run --rm --build jdk
# mkdir -p ${HOME}/jdk11u && DISTRO=centos DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=11 docker-compose -f docker-compose.yml run --rm --build jdk
# mkdir -p ${HOME}/jdk17u && DISTRO=centos DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=17 docker-compose -f docker-compose.yml run --rm --build jdk
# mkdir -p ${HOME}/jdk21u && DISTRO=centos DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=21 docker-compose -f docker-compose.yml run --rm --build jdk

# mkdir -p ${HOME}/jdk11u && DISTRO=alpine DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=11 docker-compose -f docker-compose.yml run --rm --build jdk
# mkdir -p ${HOME}/jdk17u && DISTRO=alpine DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=17 docker-compose -f docker-compose.yml run --rm --build jdk
# mkdir -p ${HOME}/jdk21u && DISTRO=alpine DUMMY_UID=`id -u` DUMMY_GID=`id -g` JAVA_VERSION=21 docker-compose -f docker-compose.yml run --rm --build jdk

services:
  jdk:
    image: ${DOCKER_HUB_USER_AND_REPOSITORY}:${DISTRO}${JDK}${JAVA_VERSION}u
    build:
      dockerfile: Dockerfile.${DISTRO}
      target: ${JDK}${JAVA_VERSION}u
      args:
        - DUMMY_UID=${DUMMY_UID}
        - DUMMY_GID=${DUMMY_GID}
    hostname: ${DISTRO}${JDK}${JAVA_VERSION}u
    container_name: ${DISTRO}${JDK}${JAVA_VERSION}u
    user: ${DUMMY_UID}:${DUMMY_GID}
    working_dir: /${DUMMY_USER}/
    command: /${DUMMY_USER}/${COMPOSE_PROJECT_NAME}/entrypoint${JAVA_VERSION}.sh ${JAVA_VERSION}
    env_file:
      - .env
    volumes:
      - ${HOME}/${JDK}${JAVA_VERSION}u/:/${DUMMY_USER}/${JDK}${JAVA_VERSION}u/:rw
      - ${HOME}/${JTREG}/:/${DUMMY_USER}/${JTREG}/:rw
      - ${HOME}/${GTEST}/:/${DUMMY_USER}/${GTEST}/:rw
      - ./:/${DUMMY_USER}/${COMPOSE_PROJECT_NAME}:ro
      - ${HOME}/.github_token:/${DUMMY_USER}/.github_token:ro
