FROM aashipov/openjdk-build:alpinejdkbuilder AS downloader
ARG OPENJDK_ARCHIVE_NAME=OpenJDK11U-jdk_x64_alpine-linux_hotspot_11.0.16.1_1.tar.gz
ARG OPENJDK_ARCHIVE_IN_TMP=/tmp/${OPENJDK_ARCHIVE_NAME}
ADD https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16.1%2B1/${OPENJDK_ARCHIVE_NAME} /tmp/
RUN tar -xzf ${OPENJDK_ARCHIVE_IN_TMP} -C ${JAVA_HOME}/ --strip-components=1 && rm -rf ${OPENJDK_ARCHIVE_IN_TMP}

FROM aashipov/openjdk-build:alpinejdkbuilder  
COPY --from=downloader ${JAVA_HOME}/ ${JAVA_HOME}/
