name: openjdk-linux
run-name: "${{ inputs.vendor }} ${{ inputs.distro }} ${{ inputs.javaVersion }}"

on:
  workflow_dispatch:
    inputs:
      vendor:
        description: "vendor"
        required: true
        default: "openjdk"
        type: choice
        options:
          - "openjdk"
          - "corretto"
          - "openj9-openjdk"
      distro:
        description: "distro"
        required: true
        default: "centos"
        type: choice
        options:
          - "centos"
          - "alpine"
      javaVersion:
        description: "javaVersion"
        required: true
        default: "11"
        type: choice
        options:
          - "8"
          - "11"
          - "17"
          - "21"
          - "25"

jobs:
  openjdk-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Check if GH_TOKEN is set
        run: |
          if [ "${{ secrets.GH_TOKEN }}" == '' ]
          then
            printf "secrets.GH_TOKEN is not set\n"
            exit 1
          fi

      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Clone builder repo
        run: git clone https://github.com/aashipov/${{ inputs.vendor }}-build.git

      - name: Create host directories
        run: mkdir -p ${HOME}/{jdk{7,8,11,17,21,25}u,corretto-{8,11,17,21,25},jtreg,googletest,openj9-openjdk-jdk{8,11,17,21,25}}

      - name: Save GH_TOKEN
        run: echo ${{ secrets.GH_TOKEN }} > ${HOME}/.github_token

      - name: Change access rights
        run: sudo chown -R 10001:10001 . ${HOME}/{jdk{7,8,11,17,21,25}u,corretto-{8,11,17,21,25},jtreg,googletest,.github_token,openj9-openjdk-jdk{8,11,17,21,25}}

      - name: Build JDK
        run: ls -lA && cd ${{ inputs.vendor }}-build && cat .tag_to_build_${{ inputs.javaVersion }} && DISTRO=${{ inputs.distro }} JAVA_VERSION=${{ inputs.javaVersion }} DUMMY_UID=10001 DUMMY_GID=10001 docker compose run --rm jdk
